authenticate:
    path: /authenticate
    controller: App\Controller\UserController::authenticate
    methods: [POST]

register:
    path: /register
    controller: App\Controller\UserController::register
    methods: [POST]
